### ISSUE TITLE
Messages key only returned in some results for /game/systems/{searchTerm}/locations

### ISSUE THREAD

**Issue by ztubb** [SpaceTradersAPI/issues-and-suggestions#107]
`messages`, like `cargo`, should consistently be returned in requests. If there are no messages associated with a system, the `messages` value would be an empty array.
The current implementation only includes `messages` key when there is a value associated with the system object

**Comment by jadlers** [comment]
@ztubb sorry for not getting back to you on this sooner, would you mind to elaborate a bit?

The things I don't think I understand is the point of sending the extra property `messages` if it's empty for most responses. There's currently only a single endpoint for which not every response includes it. Perhaps you mean that for the requests which possibly could contain a message it should be an empty array when missing?

**Comment by HamishWHC** [comment]
That's how I interpreted it. I think they are confusing systems with locations?
