### ISSUE TITLE
Response to buying a new ship doesn't distinguish the new ship

### ISSUE THREAD

**Issue by jadlers** [SpaceTradersAPI/issues-and-suggestions#111]
As has been pointed out a few times before but now the last time by `staff0rd` [here](https://discord.com/channels/792864705139048469/792865721922486322/8297142126945239060)  on Discord:

> `POST users/:username/ships` should return the ship, or at least the `ship.id`. Why force `GET users/:username/ships` before buying and then a diff afterwards to identify the recently purchased ship?

**Comment by nhowell** [comment]
Possible duplicate of #90

**Comment by jadlers** [comment]
@nhowell Good find, thanks for that! It's definitely a duplicate, I'll close this one in favor of the other one!
