### ISSUE TITLE
Suggestion: Limit the places where some ships can dock

### ISSUE THREAD

**Issue by TheMadBotter** [SpaceTradersAPI/issues-and-suggestions#115]
Not all spacecraft can do everything. Landing and taking off from an atmospheric body requires aerodynamic design and heat shielding. High-gravity bodies require high-thrust engines. Long-distance travel in deep space requires radiators and efficient vacuum engines.

While there does currently seem to be a fuel penalty for taking off from locations with the `PLANET` type, all ships are perfectly capable of going everywhere. I propose to create a category of ships that are specialized for deep space travel, where landing on atmospheric or high-gravity bodies is either impossible (returns an error) or impractical (damages the ship, lowers the maximum cargo).

There could still be ships that are capable of going anywhere, but they would be less efficient. This would create an incentive more complex supply lines where long-distance ships fly between moons and different ships then shuttle to the planet's surface.

For the simplest implementation, you would only have to add an extra property to ships and return an error if a non-suitable ship tries to fly to an atmospheric or high-gravity body.

**Comment by jadlers** [comment]
This is a great idea in my personal opinion! I'll file it as a new suggestion. Anyone who has ideas and comments on the issue feel free to discuss here!
