### ISSUE TITLE
Suggestion: Adding Shipping Contracts to open up new play styles and provide income opportunity for new players and idle ships

### ISSUE THREAD

**Issue by shortjared** [SpaceTradersAPI/issues-and-suggestions#119]
One thing that could be interesting to let people a) play markets more b) make money as newer players without a ton of money is the idea of contracts. I could put out contracts that payout if someone moves stuff from location a to location b for me, or a have a contract that pays out if someone delivers `X` amount of `Y` to a structure for me.

**Comment by bahrmichael** [comment]
The first would be "courier my stuff somewhere", and the second would be "deliver X to me, no matter where you get it from", right?
