### ISSUE TITLE
Suggestion: Scrap ship response

### ISSUE THREAD

**Issue by Ironolife** [SpaceTradersAPI/issues-and-suggestions#121]
Current Response:
```json
{ "success": "Ship scrapped for 9438 credits" }
```
Suggested Response:
```json
{ "scrappedFor": 9438 }
```
or
```json
{ "credits":  123456 }
```

This would allow clients to update credits more reliably without  matching with regex or refetching the user.

**Comment by bloveless** [comment]
I would also like to second this one and vote that the new credits for the user are returned or both scrappedFor and new credits are returned.

**Comment by jsProj** [comment]
You can additionally just do this `result.success.split(" ")[3]`

**Comment by nhowell** [comment]
> You can additionally just do this `+result.success.split(" ")[3]`

Right, the OP mentioned this - i.e. the point about Regex, which is not really any different than what you're proposing here.

The issue is that parsing the credits from the string is brittle (e.g. what if the message is re-worded), and also requires extra work of the client.
