### ISSUE TITLE
Is this project still being continued?

### ISSUE THREAD

**Issue by DillonB07** [SpaceTradersAPI/issues-and-suggestions#123]
Hi,

I've started building a Flask application for this project, but was wondering if it was still being continued or if it had been abandoned? I wasn't sure as there wasn't a weekly reset and the last activity here was months ago.

**Comment by artokun** [comment]
Hey thanks for checking in.

Yes we are actually doing a complete rewrite currently to expand the universe and features as well as to improve performance. We did weekly resets initially to test the onboarding flow and balance as well as figuring out a fun progression timeline. Now we’re just letting it run while we work on the new version.

we don’t have a timeline yet to when we’ll open up the beta but in our discord we occasionally post updates with progress

**Comment by DillonB07** [comment]
Thanks! I'll keep working on my implementation.
I don't have access to Discord, but I'll keep an eye on the changelog.
