### ISSUE TITLE
Survey deposits not covered by signature

### ISSUE THREAD

**Issue by crisman** [SpaceTradersAPI/issues-and-suggestions#124]
Given a valid survey like so:

`{"signature":"X1-UK8-23715D-6C648F","symbol":"X1-UK8-23715D","deposits":[{"symbol":"AMMONIA_ICE"},{"symbol":"IRON_ORE"},{"symbol":"QUARTZ_SAND"},{"symbol":"SILICON_CRYSTALS"}],"expiration":"2023-02-15T09:45:23.131Z","size":"SMALL"}`

If the `"symbol"` values in the `"deposits"` list are manually replaced like so:

`{"signature":"X1-UK8-23715D-6C648F","symbol":"X1-UK8-23715D","deposits":[{"symbol":"DIAMONDS"},{"symbol":"DIAMONDS"},{"symbol":"DIAMONDS"},{"symbol":"DIAMONDS"}],"expiration":"2023-02-15T09:45:23.131Z","size":"SMALL"}`

and an `/extract survey=` call gets extraction yields that are always `"DIAMONDS"`.

Seems to work for any valid trade symbol.  `"MANGOS"` generated an unexpected error.  Worked with

```
"DIAMONDS"
"ANTIMATTER"
"PRECIOUS_STONES"
"ENGINE_ION_DRIVE_II"
```

Yes, I was able to yield a space ship engine from extraction which sold at the orbital like a normal trade good.

Expected result for the `/extract survey=` call was a 4220 error:

```
{
    "error": {
        "code": 4220,
        "message": "Ship survey has an invalid signature."
    }
}
```

**Comment by space-admiral** [comment]
Thanks so much for reporting! Found the error and deploying a fix for this. Cheers 🎉 

Brilliant that you were able to "extract" Ion Drives from that asteroid field. I had no idea pirates were running a black market out there 😹
