### ISSUE TITLE
JSON canonicalization before signature please

### ISSUE THREAD

**Issue by crisman** [SpaceTradersAPI/issues-and-suggestions#125]
After the fix for https://github.com/SpaceTradersAPI/issues-and-suggestions/issues/124 (thank you kindly for the quick response) the signature validation seems to skip a canonicalization step.

Using httpie as in the quickstart for v2 it helpfully sorts the JSON object:

```
        "surveys": [
            {
                "deposits": [
                    {
                        "symbol": "ALUMINUM_ORE"
                    },
                    {
                        "symbol": "AMMONIA_ICE"
                    },
                    {
                        "symbol": "SILICON_CRYSTALS"
                    },
                    {
                        "symbol": "SILICON_CRYSTALS"
                    },
                    {
                        "symbol": "SILVER_ORE"
                    }
                ],
                "expiration": "2023-02-17T03:10:38.263Z",
                "signature": "X1-SN36-53875A-DCF627",
                "size": "SMALL",
                "symbol": "X1-SN36-53875A"
            }
        ]
```

Notice the order in the object is deposits, expiration, signature, size, symbol.

If that first survey result is passed back to an `/extract survey=JSON` call
```
{"deposits":[{"symbol":"ALUMINUM_ORE"},{"symbol":"AMMONIA_ICE"},{"symbol":"SILICON_CRYSTALS"},{"symbol":"SILICON_CRYSTALS"},{"symbol":"SILVER_ORE"}],"expiration":"2023-02-17T03:10:38.263Z","signature":"X1-SN36-53875A-DCF627","size":"SMALL","symbol":"X1-SN36-53875A"}
```

it returns an error:

```
{
    "error": {
        "code": 4220,
        "message": "Ship survey has an invalid signature."
    }
}
```

If the survey is reordered as it is returned from the `/survey` call with
the order in the object is signature, symbol, deposits, expiration, size
then it works fine with the expected `extraction` object returned.

```
{"signature":"X1-SN36-53875A-DCF627","symbol":"X1-SN36-53875A","deposits":[{"symbol":"ALUMINUM_ORE"},{"symbol":"AMMONIA_ICE"},{"symbol":"SILICON_CRYSTALS"},{"symbol":"SILICON_CRYSTALS"},{"symbol":"SILVER_ORE"}],"expiration":"2023-02-17T03:10:38.263Z","size":"SMALL"}
```

Please update the signature generation/check code with a canonicalization step before the signature so that JSON object ordering does not break anything.

**Comment by space-admiral** [comment]
Thanks for pointing this out, just pushed a fix to run the survey data through a canonicalization step before running verification on the signature 🏄🏻 

Let me know if you still see this issue and appreciate the details above!
