### ISSUE TITLE
Bug: No local waypoint data without chart

### ISSUE THREAD

**Issue by crisman** [SpaceTradersAPI/issues-and-suggestions#126]
# Bug: No local waypoint data without chart

## Bug Summary:

- Trying to view a local (ship present) waypoint does not show any details:

```json
{
    "data": {
        "orbitals": [],
        "symbol": "X1-CH93-29911A",
        "systemSymbol": "X1-CH93",
        "traits": [
            {
                "description": "",
                "name": "Uncharted",
                "symbol": "UNCHARTED"
            }
        ],
        "type": "MOON",
        "x": 9,
        "y": -8
    }
}
```

If I can't see the data before I chart how do I know if I want to keep the waypoint details secret?

Given the description for the API path "/systems/{systemSymbol}/waypoints" "...System must be charted or a ship must be present to return waypoint details." I had expected that at least one of `/systems/{systemSymbol}/waypoints` or `/my/ships/{shipSymbol}/scan/waypoints` would provide data before a chart.

## Reproduction Steps:

- Given a ship in orbit at a waypoint:

```json
{
  "nav": {
    "systemSymbol": "X1-CH93",
    "waypointSymbol": "X1-CH93-29911A",
    "route": {
      "departure": {
        "symbol": "X1-CH93-93050F",
        "type": "PLANET",
        "systemSymbol": "X1-CH93",
        "x": 9,
        "y": -8
      },
      "destination": {
        "symbol": "X1-CH93-29911A",
        "type": "MOON",
        "systemSymbol": "X1-CH93",
        "x": 9,
        "y": -8
      },
      "arrival": "2023-02-17T11:07:18.485Z"
    },
    "status": "IN_ORBIT",
    "flightMode": "CRUISE"
  }
}
```

- System/waypoint api says uncharted `/systems/X1-CH93/waypoints/X1-CH93-29911A`

```json
{
  "systemSymbol": "X1-CH93",
  "symbol": "X1-CH93-29911A",
  "type": "MOON",
  "x": 9,
  "y": -8,
  "orbitals": [],
  "traits": [
    {
      "symbol": "UNCHARTED",
      "name": "Uncharted",
      "description": ""
    }
  ]
}
```

- A ship scan `/my/ships/{shipSymbol}/scan/waypoints` also shows only uncharted data (just showing specific waypoint item for this waypoint):

```json
{
  "systemSymbol": "X1-CH93",
  "symbol": "X1-CH93-29911A",
  "type": "MOON",
  "x": 9,
  "y": -8,
  "orbitals": [],
  "traits": [
    {
      "symbol": "UNCHARTED",
      "name": "Uncharted",
      "description": ""
    }
  ]
}
```

## Possible Solutions:

Please make both system//waypoints and my/ships//scan/waypoints calls return details for a waypoint if the agent asking has a ship present at the waypoint.

**Comment by space-admiral** [comment]
Awesome thanks for the report, updated both the scan and systems/waypoints endpoints to return full details of waypoints with a ship present.
