### ISSUE TITLE
Suggestion: Run an Airnode to allow creation of smart contracts based on game state

### ISSUE THREAD

**Issue by bbenligiray** [SpaceTradersAPI/issues-and-suggestions#127]
[Airnode](https://docs.api3.org/explore/airnode/what-is-airnode.html) is an oracle node designed to be operated by API providers. It enables smart contracts to make API requests in a trust-minimized way. The point is to create trustless agreements such as "You will get paid $X if you can have this API endpoint return this value".

You can use [ChainAPI](https://chainapi.com/) to integrate your API and deploy an Airnode. Then you'd only need to document your endpoints for smart contract developers to use (see [this](https://docs.api3.org/reference/qrng/providers.html) for a basic example).

**Comment by space-admiral** [comment]
Hey just wanted to ping you before archiving this repo, we're redirecting all issues to be filed here: https://github.com/SpaceTradersAPI/api-docs
