### ISSUE TITLE
Add user controlled metadata to ships

### ISSUE THREAD

**Issue by jadlers** [SpaceTradersAPI/issues-and-suggestions#18]
**Note:** This issue was updated to reflect the discussion part way through.

Add a limited storage space for users to add metadata to their ships.

**Comment by ramonGonzEdu** [comment]
I personally dislike this one

**Comment by HamishWHC** [comment]
@ramonGonzEdu Why?

Personally, I think it should not be limited to nicknames, but instead you can attach a JSON object to ships (maybe locations too? would be user-specific!) that could include a nickname property. That way, your code can keep track of its state without having to maintain a separate DB that could become out of sync with the game's. Would make having multiple programs working together easier (e.g. you add a program property to a ships metadata that keeps track of which program is controlling it or its purpose, like is this part of my fleet of market-crawlers, or one of my haulers?).

**Comment by ramonGonzEdu** [comment]
@HamishWHC That idea sounds so much better, although I'd make it a specific length (4kb?) block of data/text which you can populate with anything (so you can't upload 4gb of json onto a ship; limited at 4kb and you can put json in it if wanted)

**Comment by HamishWHC** [comment]
Good point, limiting to JSON is a bad idea. And we definitely want to limit the size lol! It may also be good to allow players to have 'public' and 'private' data. Some is accessible by other players to communicate what the ship is doing or something. Not as useful tho.

**Comment by ramonGonzEdu** [comment]
that seems like a perfect suggestion, maybe make a separate issue or ask jadler to modify the issue desc

**Comment by HamishWHC** [comment]
@jadlers Could we change the issue desc to include this 'metadata' idea, with both public and private data.

@ramonGonzEdu This may be starting to get a little too much, but what about all players can apply private metadata to all objects (ships, flight plans, locations), but the owner can apply public data. This would enable people to apply their own state to other people's ships. But would end up having a lot of data. Maybe private data on other's objects has a lower limit?

**Comment by ramonGonzEdu** [comment]
I believe private data on other ppl's ships is a bit out of scope and introduces much more data without a cost (since you have to buy your own ships to put data on them, unlike just finding random ships and putting the maximum on them)

**Comment by HamishWHC** [comment]
That's true. Stick to private/public data set by owner then.

**Comment by jadlers** [comment]
@HamishWHC Since the suggestion of nicknames is already accepted I'll update both the title and description of **this** issue and change the suggestion to be pending instead. It's a cool idea for sure, but one that needs a new internal discussion. I will also create a new accepted issue for adding nicknames and link to this issue there.

**Comment by DotEfekts** [comment]
I'd caution against giving a single non-standardised data field. If you want to run two different tools that both try and use it, they could end up writing over each other and clashing. For private data, one option might be to offer a general metadata table where tools can store all the serialised data they need to. Perhaps it could cost a certain amount of credits to gain a slot, so you have to buy more space for each tool you want to use. For public data I'd recommend standardised fields.

**Comment by HamishWHC** [comment]
public should probably be standardised, and JSON seems the natural choice for that. Private though I feel should be per ship/object, as otherwise you could end up with data that refers to deleted ships. Much like currently, tools should just be careful to write to fields they can reasonably expect to be empty, just as current tools could write to a ship that is being operated by another program.

**Comment by ericgroom** [comment]
What would be the use case for this? We are given an id so it should be very easy to keep any application specific data locally in a database, file, or in memory. Given that this project is for learning, these are very useful skills to learn.

**Comment by HamishWHC** [comment]
Of course, but no one is writing a single program that does everything - they're writing 3 scripts plus a web app or smth. The idea being that this isn't a replacement for a database/local state, but instead a _way to communicate state between applications_ - like "this is being used by the hauling script don't touch it thanks" (in JSON form).
