### ISSUE TITLE
Bug: Buying a ship without funds

### ISSUE THREAD

**Issue by HOWZ1T** [SpaceTradersAPI/issues-and-suggestions#29]
Bug Summary:

- When attempting to buy a ship with insufficient funds, the error is returned as html instead of json.

Reproduction Steps:

- Attempt to buy ship with insufficient funds.

Possible Solutions:

- Change error to be returned as json instead of html.

Current HTML Error Response:
`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: User has insufficient funds to purchase ship.<br> &nbsp; &nbsp;at Function.purchaseShip (/home/joelbrubaker/api-server/server/src/modules/Ship.ts:72:13)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:93:5)<br> &nbsp; &nbsp;at /home/joelbrubaker/api-server/server/src/routes/user/ship.ts:73:5</pre>
</body>
</html>`

**Comment by artokun** [comment]
we have this fix ready to go on our next bug PR batch
