### ISSUE TITLE
Get rid of the /users/Username/ prefix.

### ISSUE THREAD

**Issue by HamishWHC** [SpaceTradersAPI/issues-and-suggestions#32]
You can't access the purchase orders/sell orders/flight plans/ etc of other players. If you can in future, then this can be added back, but I think it makes more sense for your token to identify you. So the endpoints should be:

```
/purchase-orders
/sell-orders
/flight-plans
/ships
/loans
```

The user summary endpoint could be used for looking up other players and getting info about them.
To get your own user summary, maybe `/` or `/me`?

**Comment by ramonGonzEdu** [comment]
Ah; I thought this was accepted and planned as an update

**Comment by artokun** [comment]
It’s too hard to implement with alpha but I think beta is heading this direction

**Comment by thebrubaker** [comment]
It's probably a big enough change that we wouldn't roll it out on the current endpoints, but we could make a change when we deploy V1. You alluded to the idea - at some point you can make a service that is authorized to control other player's assets. We need endpoints per user in that instance, but its also true it will be a while before we get to oauth.

I think as a compromise we can make an endpoint for `/me` or `/self` (or something better, I could never think of a good prefix) and that would allow the existing endpoints to work.

I'll explore too seeing if just no prefix, just root resources, would assume a `me` context. I don't want to lock is in too much, but its worth experimenting with. We'll make some updates for when we deploy our first `/v1` set of API endpoints.

**Comment by ramonGonzEdu** [comment]
There shouldn't really be custom endpoints for "controlling other players"
as the server should know what token is for what player; i.e a service has
an oauth token for each player and the server finds what user the token is
for in the db.

I do like the idea of having a /self prefix, but not a /me since me usually
refers to a person, while self is more generalized.

**Comment by thebrubaker** [comment]
🤦  oh man you're totally right. I don't know why my brain was stuck on needing explicit user routes. I agree then, we can strip the username prefix entirely. Thanks for pushing back on this!

**Comment by thebrubaker** [comment]
Ironically Art has been pushing for this for a while but I always strongarm him into doing what I want 😂
