### ISSUE TITLE
Suggestion: Supply and Demand Forces, Combat Planet Stripping

### ISSUE THREAD

**Issue by HOWZ1T** [SpaceTradersAPI/issues-and-suggestions#37]
With systems currently being stripped dry and impacting player experience, a solution is needed.

First of all, I believe that all systems where ships are purchased generate fuel, like X fuel every hour or so.

Then some systems should produce and consume goods certain goods.

Systems Producing goods:
- If they producing more goods than whats bought the price for said good drops until a minimum is reached. (over supply, under demand)

- If they are producing less goods than whats bought the price for said good rises (potentially even uncapped) (under supply, over demand)

Systems consuming goods:
- If they are not getting enough goods the price at which they buy the good increases (increased demand)
- If they are getting too much goods the price at which they buy said good decreases (decreased demand)

A simple demand supply force like this can keep planets from being completely stripped, incentivise players to establish trade routes, and let players have a direct effect on the market.

**Comment by j-spacetrader-api** [comment]
There is now a basic feature running for market forces which we will continue to expand.
