### ISSUE TITLE
Bug: Purchase Orders for Not-Owned Ships

### ISSUE THREAD

**Issue by gregorkrambs** [SpaceTradersAPI/issues-and-suggestions#39]
I would assume this bug is quite critical. 

You can create a different account, take out a ENTERPRISE loan right away and purchase orders right into your main account's cargo by supplying a non-owned shipId.

**Comment by thebrubaker** [comment]
Again, greatly appreciate you filing this issue! Super critical, I'll try to squeeze a fix in over lunch today.
