### ISSUE TITLE
ships can accidentally end up with a massive cargohold

### ISSUE THREAD

**Issue by artokun** [SpaceTradersAPI/issues-and-suggestions#40]
Maybe an unsigned int?
need to guard againts this

```js
}
user: REDACTED
Credits: 2147479021
{
  credits: REDACTED,
  order: [ { good: 'FUEL', quantity: 1, pricePerUnit: 13, total: 13 } ],
  ship: {
    id: 'REDACTED',
    location: 'OE-G4',
    cargo: [ [Object], [Object] ],
    spaceAvailable: 191079276,
    type: 'JW-MK-I',
    class: 'MK-I',
    maxCargo: 100,
    speed: 2,
    manufacturer: 'Jackshaw',
    plating: 5,
    weapons: 5
  }
}```

**Comment by ramonGonzEdu** [comment]
maybe this is from when ppl bought negative amounts which made the space go up by a lot

**Comment by artokun** [comment]
> maybe this is from when ppl bought negative amounts which made the space go up by a lot

Yes, that might be actually what happened! Good insight!

**Comment by thebrubaker** [comment]
ShipGood quantities are negative which results in the high space count. Investigating.

**Comment by thebrubaker** [comment]
I think this is a result of us not having a lock on marketplace transactions. Going to implement a single queue for now that processes all transactions and will guarantee results.

**Comment by thebrubaker** [comment]
I'm going to close this because we fixed the volume calculation. Please re-open if it persists.
