### ISSUE TITLE
Add colors and random seed to planets/asteroids

### ISSUE THREAD

**Issue by ramonGonzEdu** [SpaceTradersAPI/issues-and-suggestions#42]
Adding a list of 2 or 3 colors + a random seed (for shape randomness) could be very beneficial to have planet visualizers also show the planets state.

some examples could include a simple blue/green/yellow for new planets, with a more complex grey/light blue for the very civilized planets. This would allow visualizers to be somewhat consistent in how planets are displayed and allow users to move from one platform to another and still recognise the color schemes.

**Comment by ramonGonzEdu** [comment]
This is definetly not needed and could be implemented client-side, but I think having it be shared by all clients could be useful when switching.

**Comment by artokun** [comment]
I see this as being handled client-side by just looking at the market goods being sold in your case.

Ideally we add some basic flavor to the systems and planets. i.e star type and planet size, radius, atmosphere, pressure, etc. Then we let the clients figure out what they look like based on those seeded parameters
