### ISSUE TITLE
Return ship flight plans when queried by ID

### ISSUE THREAD

**Issue by artokun** [SpaceTradersAPI/issues-and-suggestions#47]

**Comment by bchoii** [comment]
I realized I cannot query flightplan.

Then I though, I actually had it at one time when I created a flight path. I could have saved it then.
It is not critical information, having it missing doesn't affect gameplay.
In fact, missing it would even encourage developers to build their own cache.

This would further have a side effect of decreasing unnecessary, uncritical API loads on the server. You already have the data. You should not need to keep querying for it.

This could help differentiate between good enough clients and great, advanced clients.

There is merit in NOT having the ability to query flightplan.

**Comment by bchoii** [comment]
I realized I cannot query flightplan.

Then I thought, I actually had it at one time when I created a flight path. I could have saved it then.
It is not critical information, having it missing doesn't affect gameplay greatly other than waiting for the ship to eventually arrive.
In fact, missing it would even encourage developers to build their own cache.

This would further have a side effect of decreasing unnecessary, uncritical API loads on the server. You already have the data. You should not need to keep querying for it.

This could help differentiate between good enough clients and great, advanced clients.

There is merit in NOT having the ability to query flightplan.

**Comment by bchoii** [comment]
I realized I cannot query flightplan.

Then I thought, I actually had it at one time when I created a flight path. I could have saved it then.
It is not critical information, having it missing doesn't affect gameplay greatly other than just waiting for the ship to eventually arrive.
In fact, missing it would even encourage developers to build their own cache.

This would further have a side effect of decreasing unnecessary, uncritical API loads on the server. You already have the data. You should not need to keep querying for it.

This could help differentiate between good enough clients and great, advanced clients.

There is merit in NOT having the ability to query flightplan.

**Comment by bchoii** [comment]
I realized I cannot query flightplan.

Then I thought, I actually had it at one time when I created a flight path. I could have saved it then.
It is not critical information, having it missing doesn't affect gameplay greatly other than not knowing when the ship will arrive.
In fact, missing it would even encourage developers to build their own cache.

*This would further have a side effect of decreasing unnecessary, uncritical API loads on the server.* You already have the data. You should not need to keep querying for it.

This could help differentiate between good enough clients and great, advanced clients.

There is merit in NOT having the ability to query flightplan.

**Comment by artokun** [comment]
Very true, maybe we just don’t eager load it with the list of user ships as I’d the case currently, but the app is intended to be newbie friendly so it might help have a single user ship endpoint that loads in the flight plan? Once we add in a cost to the request, that could potentially encourage caching instead of pinging updates constantly. I think caching should at least be recommended as a step before creating a flight plan in the api and tutorial.

Great insight!

**Comment by bchoii** [comment]
Yes.

I can imagine a situation where clients abuse this API to update their ship movement, every few seconds.

**Comment by HamishWHC** [comment]
However, many clients are stateless and do not create the flight plans themselves, but are a way to monitor other applications actually creating flight plans.

**Comment by HamishWHC** [comment]
@artokun Has this been added or has it been rejected?

**Comment by artokun** [comment]
My bad, forgot to flip the tag when I closed it
