### ISSUE TITLE
Add shortcodes for errors

### ISSUE THREAD

**Issue by ramonGonzEdu** [SpaceTradersAPI/issues-and-suggestions#53]
Add simple shortcodes in json errors so that they now have 3 properties: the id: 404/401, the text message, and a shortcode like "INVALID_TOKEN" or "NO_TOKEN" for easier parsing on clients and also allowing the server to change the long text message. This also allows for client side localization of error codes.

**Comment by HamishWHC** [comment]
Adding short names is a good idea. I would also argue for removing the HTTP error code, as that is already provided as part of a normal response.

**Comment by thebrubaker** [comment]
Love this idea, we will definitely take this on.

**Comment by ramonGonzEdu** [comment]
> Adding short names is a good idea. I would also argue for removing the HTTP error code, as that is already provided as part of a normal response.

I like the HTTP error code in the json as it's simpler to handle in the js fetch api, since you can just 
```js
await fetch(url, opts).then(x=>x.json())
```
and it'll include the http error code, but adding the shortcodes would make the http code somewhat redundant

**Comment by HamishWHC** [comment]
x.status is the status code tho? With shortcodes though even that is redundant.

**Comment by ramonGonzEdu** [comment]
x.status is the the status code, but that would require caching the value of x and then calling the x.json call and muddling the code. It is still redundant if the shortcodes are added.
using x.status would give
```js
const [json, status] = await fetch(url, opts).then(x=>Promise.all([x.json(),new Promise(res=>res(x.status))]));
```
which is much more complex

**Comment by ramonGonzEdu** [comment]
The shortcodes should also be added to endpoints like https://api.spacetraders.io/game/status if the text is changed later.

**Comment by HamishWHC** [comment]
> ```js
> const [json, status] = await fetch(url, opts).then(x=>Promise.all([x.json(),new Promise(res=>res(x.status))]));
> ```

You're kidding right?
```js
const [json, status] = await fetch(url, opts).then(x=>[x.json(), x.status]);
// or
const x = await fetch(url, opts)
// now you can use x.status and x.json()
```

x.status and x.json() aren't asynchronous!

**Comment by ramonGonzEdu** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Body/json
The json() method of the Body mixin takes a Response stream and reads it to completion. It returns a *promise* that resolves with the result of parsing the body text as JSON.

**Comment by ramonGonzEdu** [comment]
x.status is synchronous, but x.json return a promise, and is async.

**Comment by HamishWHC** [comment]
Either way, your example was still over the top. Here's a revised version:
```js
const [x, json] = await fetch(url, opts).then(async x => [x, await x.json()])
```

**Comment by ramonGonzEdu** [comment]
Didn't know you could have the callback be async, although it does sound logical now that I think about it...
