### ISSUE TITLE
Include required fuel in the insufficient fuel error.

### ISSUE THREAD

**Issue by HamishWHC** [SpaceTradersAPI/issues-and-suggestions#54]
The current error returning upon trying to fly somewhere with insufficient fuel doesn't tell you how much fuel you do need, which may be frustrating or confusing for beginners.
I'd suggest the inclusion of `fuelRequired` in the base of the response object.
```json
{
    "error": {
        "code": 3001,
        "message": "Ship has insufficient fuel for flight plan."
    },
    "fuelRequired": 7
}
```

**Comment by thebrubaker** [comment]
Great idea, that really is annoying!

**Comment by ramonGonzEdu** [comment]
This might be difficult to add due to the random Element in fuel consumption that can be observed; i.e it will give you the fuel required for a flight, then give you a different cost

**Comment by HamishWHC** [comment]
Then include the maximum fuel requirement. i.e. if random element is either 0, 1 or 2 and the base cost is 5, then show 7.

**Comment by ramonGonzEdu** [comment]
Perhaps it should be the maximum fuel requirement rounded to the nearest 10, so that the function for randomness can't easily be figured out
