### ISSUE TITLE
FlightPlanProcessor needs to restart automatically when stuck

### ISSUE THREAD

**Issue by artokun** [SpaceTradersAPI/issues-and-suggestions#56]
We had a condition where flightplans were resolved, but did not update the corresponding ships with their new destination values.

Recommendation:
- Implement an alert next time that background jobs get hung up
- Stop and restart processes on hangup

**Comment by thebrubaker** [comment]
Just pushed a change to decouple the job processing from the API and also scaled the API across four CPU cores. Let's monitor and see if this issue continues, but that might resolve it.

**Comment by thebrubaker** [comment]
Added more logs to the job processor so we can see if this is failing.

**Comment by thebrubaker** [comment]
Please re-open if this happens again.
