### ISSUE TITLE
spaceAvailable not calculating correctly with new volume inventory

### ISSUE THREAD

**Issue by artokun** [SpaceTradersAPI/issues-and-suggestions#57]

**Comment by artokun** [comment]
I just landed a PR that should have fixed it. Once I get it confirmed fix we can close this issue. @jadlers can you confirm?

**Comment by jadlers** [comment]
@artokun I'll keep my eyes open for confirmation from players!

**Comment by jadlers** [comment]
@artokun It's not yet fixed properly. [bchoii confirmed on Discord](https://discord.com/channels/792864705139048469/792917401746145310/818502060793659422). There's 1000 units of cargo with space for 300.

```js
{
  id: 'ckm0cvtp71672zd89jv3v4q1f',
  cargo: [
    { good: 'FUEL', quantity: 15, totalVolume: 15 },
    { good: 'MACHINERY', quantity: 250, totalVolume: 1000 }
  ],
  spaceAvailable: 35,
  type: 'GR-MK-I',
  class: 'MK-I',
  maxCargo: 300,
}
```

**Comment by jadlers** [comment]
bchoii added a spreadsheat with data to help with fixing the issue: https://docs.google.com/spreadsheets/d/15Z8lHEtwRr2cyOB7gTHrM_E15mGNg_7yPa1C5AETFe8/edit#gid=1468807835
