### ISSUE TITLE
Rate Limiter is using IP to rate limit instead of username/account.

### ISSUE THREAD

**Issue by notVitaliy** [SpaceTradersAPI/issues-and-suggestions#63]
Each "scout" in this image has its own token and username.

![image](https://user-images.githubusercontent.com/3137491/110375531-1421cb80-8020-11eb-8201-9f32a09eb746.png)

**Comment by HamishWHC** [comment]
Considering creating users is free this seems reasonable. IMO it should do both. @jadlers What's your verdict on this?

**Comment by jadlers** [comment]
There has been some talk about this but as far as I know no decision has been made yet.

**Comment by bchoii** [comment]
Consider the case where this app is used in a classroom setting, a legitimate use case could have maybe 40 accounts on one IP...

**Comment by ericgroom** [comment]
It seems like a tough problem to prevent abuse. I know there has been talk of using oAuth and forcing people to link a social account. Maybe a quicker way would be to put account creation behind a captcha so that at least it couldn't be automated.
