### ISSUE TITLE
Ships should be able to "sell" any good at $0 price at any location.

### ISSUE THREAD

**Issue by HamishWHC** [SpaceTradersAPI/issues-and-suggestions#64]
Worst case scenario , ships should be able to "sell" any good at $0 price.
Basically the ship is dumping cargo to make space.

_Originally posted by @bchoii in https://github.com/SpaceTradersAPI/issues-and-suggestions/issues/58#issuecomment-793013684_

**Comment by Stumblinbear** [comment]
I believe being able to sell at zero isn't intuitive when you're stuck on a planet. Having a dedicated endpoint for this would go a long way towards "self explaining behavior." That said, I'd be in favor of allowing both situations.

**Comment by bchoii** [comment]
If can jettison cargo, then should be able to abandon ship as well ?
