### ISSUE TITLE
/purchase-orders "order" property should be an object not an array

### ISSUE THREAD

**Issue by HamishWHC** [SpaceTradersAPI/issues-and-suggestions#65]
Currently:
```json
{
    "credits": 105950,
    "order": [
        {
            "good": "FUEL",
            "quantity": 50,
            "pricePerUnit": 1,
            "total": 50
        }
    ],
    "ship": {...}
}
```
Since you can only purchase 1 distinct good at a time (and order is not plural), the order property should just be the object instead of an array with the object.

Note that this will likely break a lot of people's code!

**Comment by artokun** [comment]
lets queue it up for v0.0.3

**Comment by jadlers** [comment]
This is fixed and just awaits next release before it's added.

**Comment by artokun** [comment]
Sorry, not released yet! reopening
