### ISSUE TITLE
Passing JSON in create flight plan destination causes 500.

### ISSUE THREAD

**Issue by HamishWHC** [SpaceTradersAPI/issues-and-suggestions#67]
I made a mistake in my code and sent this: `{"shipId":"ckm179d66305412wx89covwn9ee","destination":{"symbol":"OE-NY","type":"ASTEROID","name":"Nyon","x":74,"y":50}}` when it should have been `{"shipId":"ckm179d66305412wx89covwn9ee","destination":"OE-NY"}`. It caused a 500 error though, so probably should be fixed.

**Comment by artokun** [comment]
you sent it as part of the body? What did your request look like? It probably didn't parse it well and went haywire

**Comment by artokun** [comment]
looks like it was just a simple validation error, @Stumblinbear is working on a fix now
