### ISSUE TITLE
Add a /system/:id endpoint with system name and possibly locations

### ISSUE THREAD

**Issue by Stumblinbear** [SpaceTradersAPI/issues-and-suggestions#68]
Would allow getting the system name without querying and filtering every system returned in `/systems`

**Comment by jadlers** [comment]
Maybe [`/game/systems/:id/locations`](https://api.spacetraders.io/#api-locations-locations) should be replaced with `/system/:id` which also includes the system name.

**Comment by Stumblinbear** [comment]
It may be useful to have both for the sake of optional granularity.
