### ISSUE TITLE
Verify rate limiting headers

### ISSUE THREAD

**Issue by artokun** [SpaceTradersAPI/issues-and-suggestions#72]
From discord:

How does the `x-ratelimit-remaining` header work? My thought was that it would be [0, `x-ratelimit-limit`) and if you made more requests after it got to `0` within the time window that you would get 429. However I've never seen this value above `1` and don't get a 429 even after making a few more requests past `0`.

**Comment by nhowell** [comment]
Possibly a duplicate of #52

**Comment by jadlers** [comment]
Closing since it it indeed a duplicate of the issue mentioned in the previous comment.
