### ISSUE TITLE
There's a potential for a brute-force attack

### ISSUE THREAD

**Issue by notVitaliy** [SpaceTradersAPI/issues-and-suggestions#73]
3 separate error codes returned for:
* a request to an existing username with an invalid token
* a request to an existing username but with a token for a different user
* a request to a non-existing username with a valid token

imo, all these scenarios should terminate in the same error code. Otherwise, you're giving too much information out which can be used against you.

**Comment by Stumblinbear** [comment]
Is this the case? Which error codes are returned?

**Comment by cxcorp** [comment]
Just tried this out. I got these responses:

| Token | Existing user | HTTP status | API error |
|-|-|-|-|
|   |   | 401 | 40101, Did you forget to add a bearer token to your request? |
|   | ✓ | 401 | 40101, Did you forget to add a bearer token to your request? |
| ✓ |   | 403 | 40301, You do not have access to this user or their resources. |
| ✓ | ✓ | 404 | 404, User <user> does not exist! |

I do agree, would be better to just return the same code and message for an existing user and a non-existing user to prevent user enumeration.

**Comment by j-spacetrader-api** [comment]
This should be removed and now returns a single error. Please re-open if this continues to exist.
