### ISSUE TITLE
Suggestion : Make cargo have purpose.

### ISSUE THREAD

**Issue by bchoii** [SpaceTradersAPI/issues-and-suggestions#76]
Currently, cargo is used for trading, a placeholder for price and space .

Suggestion to make cargo have purpose, eg, need to convert a certain amount of WORKERS, RESEARCH, METAL and SHIP_PARTS to buy some of the more advanced ships , not just credits.

**Comment by bchoii** [comment]
Why not just buy the cargo ?

The amount of cargo can be high, so that it implies you need to own these cargo (maybe spread over a number of ships, all congregated at the shipyard) before it can happen.

This implies gameplay elements where you need to build a fleet, you need to move them to the right place before a purchase can happen.

**Comment by bchoii** [comment]
Some of the cargo may be unlocked only at certain planets, difficult to move, etc.

**Comment by HamishWHC** [comment]
I feel like this will definitely be more used once the game has stuff like stations and planets you can own.
