### ISSUE TITLE
Standardize the "existing" and "all flight plan" responses

### ISSUE THREAD

**Issue by kurt1288** [SpaceTradersAPI/issues-and-suggestions#78]
The two routes for querying an existing and "all" flight plans return two different objects. For example, the "all" query returns a `departedAt` property while the existing route does not. The "all" also returns id values while the "existing" returns the actual string names.

Since both responses return a "flight path", I think expecting the objects to be the same isn't unreasonable.

**Comment by jadlers** [comment]
This is already fixed and live!
