### ISSUE TITLE
Viewing a flight plan for an id which does not exist gives a 500

### ISSUE THREAD

**Issue by ericgroom** [SpaceTradersAPI/issues-and-suggestions#80]
While looking at the changes to flight-plans, I accidentally passed my shipId to `GET /users/:username/flight-plans/:id` which yielded a 500 response. I think it should be a 404 or something similar instead. Pretty minor to say the least.

**Comment by jadlers** [comment]
We appreciate all report of bugs, no matter how small! Great find, thanks 🙏
