### ISSUE TITLE
Have a separate cargo capacity for fuel storage (i.e a fuel tank)

### ISSUE THREAD

**Issue by kurt1288** [SpaceTradersAPI/issues-and-suggestions#82]
I imagine implementing this wouldn't exactly be easy, but...

A fuel tank and cargo space tend to be measured separately (a car's trunk space doesn't include the fuel tank capacity, for example). Having them separate would also prevent a ship from being stuck on a planet and having to ditch cargo just to pick up more fuel.

**Comment by nhowell** [comment]
Agreed. It should still be possible to haul fuel in your cargo bay, but it would be nice if your ship had it's own fuel tank that is separate from the cargo bay, too.
