### ISSUE TITLE
Capacity to trade between ships, including within the same account

### ISSUE THREAD

**Issue by SapphicFire** [SpaceTradersAPI/issues-and-suggestions#84]
# Suggestion: Inter-ship trading, including intra-account

Feature List:
- This feature would add the capacity to move goods between ships
  - This would be possible at locations where ships are stopped/docked
  - It would allow transferring items like fuel and saleable goods between ships
  - This would possibly have a capacity to set a price for the escrow, if being performed between accounts
- This feature would include the capacity to move goods between ships on the same account
  - This could use a similar endpoint and body to the above, but eschew the credit price flag?

I am imagining the trade/transfer as a POST with a body where you specify origin and destination ships, the good you desire and a credit cost field. We'd also need a way for both parties to agree to a trade.

@artokun mentioned that this has been discussed before and asked that this be raised as a suggestion

**Comment by jadlers** [comment]
Great thing adding such a detailed suggestion, thanks! 👏 
Everyone feel free to add to the discussion should you feel like anything is missing or if we need to think about anything in particular before/when implementing (if it's added). This goes for all issues in the repo!
