### ISSUE TITLE
Make errors more digestible by automated systems and clients

### ISSUE THREAD

**Issue by ericgroom** [SpaceTradersAPI/issues-and-suggestions#87]
Currently errors come back in the form of:
```json
{
  "error": {
    "message": "A message",
    "code": 3001
  }
}
```

There are two things I want to suggest:
1. Documentation on the different error codes.
2. Potentially adding additional fields that are easy to parse.

I think the first is self explanatory.

The second would be very nice for those of us writing wrappers and SDKs which are used in automated systems. For instance if I'm trying to create a flight plan and don't have enough fuel I get this back:
```json

"error": {
   "code": 3001,
   "message": "Ship has insufficient fuel for flight plan. You require 41 more FUEL"
}

```
Which is great if you yourself see the message, but I think there should be an additional field such as `"fuel_missing": 41` so that an automated system could easily recover from the error without having to parse a string for the fuel.

**Comment by thebrubaker** [comment]
I like this idea. We could add a property for data (or a better suggested prop name) that will contain values for the context of the error.
