### ISSUE TITLE
How long do tokens last?

### ISSUE THREAD

**Issue by trozware** [SpaceTradersAPI/issues-and-suggestions#92]
I set up a user account and created a token on Sunday 14th March 2021.
I tested numerous API calls that all worked well.

Today (Tuesday 16th March), no API calls that require a token will work.
For every call, I get back:
`{"error":{"message":"Token was invalid or missing from the request. Did you confirm sending the token as a query parameter or authorization header?","code":40101}}`

Then I tried making a new token and that worked which goes against the statement in the docs that says "You can only generate a single token once per username.".

So do I need to create a new token every day or some other period?

**Comment by DotEfekts** [comment]
While the game is in alpha there is a weekly reset on Sunday night PST. You'll need to make a new account each week.

**Comment by trozware** [comment]
Ah, thank you. I had not realised this.
